# -*- coding: utf-8 -*-
"""seed_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jthXa1QXH0ieuWr1tRq8BSeXhTKOQ_p3
"""

# Seeding for Reproducibility

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)  # if using multi-GPU

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)